services:
  mysql:
    image: mysql:8.0
    container_name: cafe-francais_mysql_dev
    environment:
      MYSQL_ROOT_PASSWORD: roots
      MYSQL_DATABASE: cafe-francais
      MYSQL_USER: cafe-francais
      MYSQL_PASSWORD: cafe-francais
    volumes:
      - mysql_dev_data:/var/lib/mysql
    networks:
      - cafe-francais_network
    command: >
      --default-authentication-plugin=mysql_native_password --skip-name-resolve
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-ucafe-francais", "-pcafe-francais" ]
      interval: 5s
      timeout: 3s
      retries: 10

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
      target: dev
    container_name: cafe-francais_backend_dev
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DATABASE_URL: mysql://root@127.0.0.1:3306/cafe-francais
      APP_ENV: dev
      APP_DEBUG: 1
      XDEBUG_MODE: off
    volumes:
      # Monte le code source
      - ./backend:/app
      # EXCLUSIONS des dossiers lourds (volumes nommés à la place)
      - backend_vendor:/app/vendor
      - backend_var:/app/var
    networks:
      - cafe-francais_network

  nginx_backend:
    image: nginx:alpine
    container_name: cafe-francais_nginx_backend_dev
    depends_on:
      - backend
    ports:
      - "8080:80"
    volumes:
      - ./backend/public:/app/public:ro
      - ./docker/nginx/backend.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - cafe-francais_network

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      target: dev
    container_name: cafe-francais_frontend_dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
      
    networks:
      - cafe-francais_network

volumes:
  mysql_dev_data:
  backend_vendor:
  backend_var:
  frontend_node_modules:


networks:
  cafe-francais_network:
    driver: bridge