nelmio_cors:
  defaults:
    origin_regex: false
    allow_origin: ['http://localhost:5173']
    allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
    allow_headers: ['Content-Type', 'Authorization']
    max_age: 3600

  paths:
    '^/api/':
      allow_origin: ['http://localhost:5173']
      allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
      allow_headers: ['Content-Type', 'Authorization']
      max_age: 3600
